{% set version = '1.8-25' %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-mgcv
  version: {{ version|replace("-", "_") }}

source:
  fn: mgcv_{{ version }}.tar.gz
  url:
    - {{ cran_mirror }}/src/contrib/mgcv_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/mgcv/mgcv_{{ version }}.tar.gz
  sha256: 586cf3300056ccb3689e7a3351238d9aedc69e8df541183be322df42b6c159f8

build:
  merge_build_host: True  # [win]
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ compiler('c') }}        # [not win]
    - {{native}}toolchain        # [win]
    - {{posix}}filesystem        # [win]
    - {{posix}}make
    - {{posix}}sed               # [win]
    - {{posix}}coreutils         # [win]
    - {{posix}}zip               # [win]
  host:
    - r-base
    - r-matrix
    - r-nlme >=3.1_64
  run:
    - r-base
    - {{native}}gcc-libs         # [win]
    - r-matrix
    - r-nlme >=3.1_64

test:
  commands:
    - $R -e "library('mgcv')"           # [not win]
    - "\"%R%\" -e \"library('mgcv')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=mgcv
  license: GPL (>= 2)
  summary: Generalized additive (mixed) models, some of their extensions and  other generalized
    ridge regression with multiple smoothing  parameter estimation by (Restricted) Marginal
    Likelihood,  Generalized Cross Validation and similar. Includes a gam()  function,
    a wide variety of smoothers, JAGS support and  distributions beyond the exponential
    family.
  license_family: GPL3
  license_file: '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3'  # [unix]
  license_file: '{{ environ["PREFIX"] }}\R\share\licenses\GPL-3'  # [win]

extra:
  recipe-maintainers:
    - dpryan79
    - johanneskoester
    - bgruening
    - daler
    - jdblischak
    - cbrueffer
