{% set version = '1.8-24' %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-mgcv
  version: {{ version|replace("-", "_") }}

source:
  fn: mgcv_{{ version }}.tar.gz
  url:
    - {{ cran_mirror }}/src/contrib/mgcv_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/mgcv/mgcv_{{ version }}.tar.gz
  sha256: a9f8e9823f6d6a4a568d151f2fa619bb2811df73c013e9a105720d9b32b4740c

build:
  merge_build_host: True  # [win]
  number: 1002
  skip: true  # [win32]
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ compiler('c') }}        # [not win]
    - {{native}}toolchain        # [win]
    - {{posix}}filesystem        # [win]
    - {{posix}}make
    - {{posix}}sed               # [win]
    - {{posix}}coreutils         # [win]
    - {{posix}}zip               # [win]
    - llvm-openmp                # [osx]
  host:
    - r-base
    - r-matrix
    - r-nlme >=3.1_64
  run:
    - r-base
    - {{native}}gcc-libs         # [win]
    - r-matrix
    - r-nlme >=3.1_64
    - llvm-openmp                # [osx]

test:
  commands:
    - $R -e "library('mgcv')"           # [not win]
    - "\"%R%\" -e \"library('mgcv')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=mgcv
  license: GPL (>= 2)
  summary: Generalized additive (mixed) models, some of their extensions and  other generalized
    ridge regression with multiple smoothing  parameter estimation by (Restricted) Marginal
    Likelihood,  Generalized Cross Validation and similar. Includes a gam()  function,
    a wide variety of smoothers, JAGS support and  distributions beyond the exponential
    family.
  license_family: GPL3
  license_file: '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3'

extra:
  recipe-maintainers:
    - johanneskoester
    - bgruening
    - daler
    - jdblischak
    - cbrueffer
