travis:
  secure:
    BINSTAR_TOKEN: rK//GOiuLDvFefoZeviaaiTcTrq5xv3AvH5o/lTGexGLf7KGJ80lc3gyqlQzz4JM9TTcjoOE3EkHBTBYR1JJiwCgjJHzikcAiEvxKPhPzPCK6PGoIDDLeOpz3NlTW07dqm5z+jupSF6ZkvFoEhboQpz2Bklb3XM9chQUAB+7I4wqOFbeCdwgPe5J3tb0iYOxzKIAnAGj6EX2Cr3GeSwl0dcZGKrfQZXc1Nlk6iYgFUhZFT223oLVTpegIL/4bltIaips5IRfWdCPHU8BilpPjNikFIi0U71w9uMM1LvooywZe2ogt/XpPtJkjKkuM9U2XrpzpiGFsEjwuga9L5QBW9jRP3qj9k+lzJfEvUx+jKGJgF7xFp7Ic63hauZiPzopODiDd3SNXZivQ6di/AoT45nwqFv+EkRY/OWgS7M+wZjswv22+9GKE1XW7FA6PCIhTpMMpOfIvgXZiu1WxuDvC89ai2Ocs7u24MfbagZRYkyIe+CrSOOVth9JCsvF1yzYvCu5El2WGV1t8rhXec6x3G1jLRtINlSfTmbvOHmDkTraLmcTS1jklqqRhrjsq7WxhRtC8iDYeylqF2WcCe1OYAKOV1+gaJ2xxJFbI0u6TrEyJLqP4E7ReEs3kOWDH+R51a0ofc2BGvwHgw5t3sMfdU19uBQzqxNgPSQLId2ZIKg=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
